2022-10-31T19:19:16: PM2 log: ===============================================================================
2022-10-31T19:19:16: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
2022-10-31T19:19:16: PM2 log: Time                 : Mon Oct 31 2022 19:19:16 GMT+0700 (Western Indonesia Time)
2022-10-31T19:19:16: PM2 log: PM2 version          : 5.2.2
2022-10-31T19:19:16: PM2 log: Node.js version      : 18.10.0
2022-10-31T19:19:16: PM2 log: Current arch         : arm64
2022-10-31T19:19:16: PM2 log: PM2 home             : /data/data/com.termux/files/home/.pm2
2022-10-31T19:19:16: PM2 log: PM2 PID file         : /data/data/com.termux/files/home/.pm2/pm2.pid
2022-10-31T19:19:16: PM2 log: RPC socket file      : /data/data/com.termux/files/home/.pm2/rpc.sock
2022-10-31T19:19:16: PM2 log: BUS socket file      : /data/data/com.termux/files/home/.pm2/pub.sock
2022-10-31T19:19:16: PM2 log: Application log path : /data/data/com.termux/files/home/.pm2/logs
2022-10-31T19:19:16: PM2 log: Worker Interval      : 30000
2022-10-31T19:19:16: PM2 log: Process dump file    : /data/data/com.termux/files/home/.pm2/dump.pm2
2022-10-31T19:19:16: PM2 log: Concurrent actions   : 2
2022-10-31T19:19:16: PM2 log: SIGTERM timeout      : 1600
2022-10-31T19:19:16: PM2 log: ===============================================================================
2022-10-31T19:20:06: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:20:06: PM2 log: App [haikal:0] online
2022-10-31T19:20:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:20:06: PM2 error: Error while calling "getconf CLK_TCK" Error: Command failed: getconf CLK_TCK
/data/data/com.termux/files/usr/bin/sh: 1: getconf: not found

    at ChildProcess.exithandler (node:child_process:412:12)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:552:15)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:552:15)
    at Pipe.<anonymous> (node:net:313:12)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'getconf CLK_TCK'
}
2022-10-31T19:20:06: PM2 error: Error while calling "getconf PAGESIZE" Error: Command failed: getconf PAGESIZE
/data/data/com.termux/files/usr/bin/sh: 1: getconf: not found

    at ChildProcess.exithandler (node:child_process:412:12)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:552:15)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:552:15)
    at Pipe.<anonymous> (node:net:313:12)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'getconf PAGESIZE'
}
2022-10-31T19:20:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:20:25: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:20:25: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:20:25: PM2 log: App [haikal:0] online
2022-10-31T19:20:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:20:42: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:20:42: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:20:42: PM2 log: App [haikal:0] online
2022-10-31T19:20:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:20:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:20:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:20:59: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:20:59: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:20:59: PM2 log: App [haikal:0] online
2022-10-31T19:21:00: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:07: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:10: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:18: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:19: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:21:19: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:21:19: PM2 log: App [haikal:0] online
2022-10-31T19:21:19: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:22: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:24: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:26: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:26: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:27: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:30: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:31: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:31: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:34: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:21:34: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:21:34: PM2 log: App [haikal:0] online
2022-10-31T19:21:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:36: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:37: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:37: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:39: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:40: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:44: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:48: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:48: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:49: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:50: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:21:50: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:21:50: PM2 log: App [haikal:0] online
2022-10-31T19:21:50: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:51: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:52: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:53: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:53: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:54: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:56: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:57: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:21:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:00: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:07: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:09: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:22:09: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:22:09: PM2 log: App [haikal:0] online
2022-10-31T19:22:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:10: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:18: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:19: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:19: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:22: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:24: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:24: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:25: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:22:25: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:22:26: PM2 log: App [haikal:0] online
2022-10-31T19:22:26: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:27: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:30: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:31: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:36: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:37: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:39: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:40: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:44: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:45: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:22:45: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:22:45: PM2 log: App [haikal:0] online
2022-10-31T19:22:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:48: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:49: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:50: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:51: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:51: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:52: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:53: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:54: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:56: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:56: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:57: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:22:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:00: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:05: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:23:05: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:23:05: PM2 log: App [haikal:0] online
2022-10-31T19:23:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:07: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:10: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:18: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:19: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:22: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:24: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:23:24: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:23:24: PM2 log: App [haikal:0] online
2022-10-31T19:23:24: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:26: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:27: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:30: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:31: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:36: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:37: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:39: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:40: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:42: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:23:42: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:23:42: PM2 log: App [haikal:0] online
2022-10-31T19:23:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:44: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:48: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:49: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:50: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:51: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:52: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:52: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:53: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:54: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:56: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:57: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:23:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:00: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:02: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:24:02: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:24:02: PM2 log: App [haikal:0] online
2022-10-31T19:24:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:07: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:10: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:18: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:19: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:22: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:24:22: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:24:22: PM2 log: App [haikal:0] online
2022-10-31T19:24:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:24: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:26: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:27: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:30: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:31: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:36: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:37: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:39: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:39: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:40: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:44: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:48: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:49: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:49: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:24:49: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:24:49: PM2 log: App [haikal:0] online
2022-10-31T19:24:50: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:51: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:52: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:52: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:53: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:54: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:56: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:57: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:24:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:00: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:07: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:10: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:12: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:25:12: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:25:12: PM2 log: App [haikal:0] online
2022-10-31T19:25:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:18: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:19: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:22: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:24: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:26: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:27: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:27: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:25:27: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:25:27: PM2 log: App [haikal:0] online
2022-10-31T19:25:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:30: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:31: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:36: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:37: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:39: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:40: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:40: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:25:40: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:25:40: PM2 log: App [haikal:0] online
2022-10-31T19:25:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:44: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:48: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:49: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:50: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:51: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:52: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:53: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:53: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:54: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:56: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:57: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:58: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:25:58: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:25:58: PM2 log: App [haikal:0] online
2022-10-31T19:25:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:25:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:00: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:07: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:07: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:10: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:18: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:18: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:26:18: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:26:19: PM2 log: App [haikal:0] online
2022-10-31T19:26:19: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:22: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:22: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:24: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:26: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:27: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:30: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:31: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:36: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:37: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:39: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:40: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:43: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:26:43: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:26:43: PM2 log: App [haikal:0] online
2022-10-31T19:26:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:44: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:48: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:49: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:50: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:51: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:52: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:53: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:54: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:56: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:57: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:26:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:00: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:07: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:10: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:10: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:27:10: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:27:10: PM2 log: App [haikal:0] online
2022-10-31T19:27:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:18: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:19: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:22: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:24: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:26: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:27: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:30: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:31: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:35: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:27:35: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:27:35: PM2 log: App [haikal:0] online
2022-10-31T19:27:36: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:37: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:39: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:40: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:44: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:48: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:49: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:50: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:51: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:52: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:53: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:53: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:54: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:56: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:27:56: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:27:56: PM2 log: App [haikal:0] online
2022-10-31T19:27:56: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:57: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:27:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:00: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:07: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:10: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:18: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:28:18: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:28:18: PM2 log: App [haikal:0] online
2022-10-31T19:28:18: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:19: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:22: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:24: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:26: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:27: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:30: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:31: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:36: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:37: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:38: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:28:38: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:28:38: PM2 log: App [haikal:0] online
2022-10-31T19:28:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:39: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:40: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:40: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:44: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:48: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:49: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:50: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:51: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:52: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:53: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:54: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:56: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:57: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:28:58: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:28:58: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:28:59: PM2 log: App [haikal:0] online
2022-10-31T19:28:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:00: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:07: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:10: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:18: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:19: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:20: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:29:20: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:29:20: PM2 log: App [haikal:0] online
2022-10-31T19:29:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:22: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:24: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:26: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:27: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:30: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:31: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:31: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:36: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:37: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:39: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:39: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:40: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:41: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:29:41: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:29:41: PM2 log: App [haikal:0] online
2022-10-31T19:29:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:44: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:48: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:49: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:50: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:51: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:52: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:53: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:54: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:54: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:56: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:57: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:29:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:00: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:01: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:30:01: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:30:01: PM2 log: App [haikal:0] online
2022-10-31T19:30:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:07: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:10: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:18: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:19: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:20: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:30:20: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:30:20: PM2 log: App [haikal:0] online
2022-10-31T19:30:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:22: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:24: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:24: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:26: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:27: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:30:37: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:30:37: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:30:37: PM2 log: App [haikal:0] online
2022-10-31T19:30:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:31:02: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:31:02: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:31:02: PM2 log: App [haikal:0] online
2022-10-31T19:31:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:31:25: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:31:25: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:31:25: PM2 log: App [haikal:0] online
2022-10-31T19:31:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:31:49: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:31:49: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:31:49: PM2 log: App [haikal:0] online
2022-10-31T19:32:08: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:32:08: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:32:08: PM2 log: App [haikal:0] online
2022-10-31T19:32:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:32:20: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:32:20: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:32:20: PM2 log: App [haikal:0] online
2022-10-31T19:32:36: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:32:36: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:32:36: PM2 log: App [haikal:0] online
2022-10-31T19:32:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:32:55: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:32:55: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:32:55: PM2 log: App [haikal:0] online
2022-10-31T19:33:13: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:33:13: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:33:13: PM2 log: App [haikal:0] online
2022-10-31T19:33:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:33:31: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:33:31: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:33:31: PM2 log: App [haikal:0] online
2022-10-31T19:33:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:33:51: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:33:51: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:33:51: PM2 log: App [haikal:0] online
2022-10-31T19:34:08: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:34:08: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:34:08: PM2 log: App [haikal:0] online
2022-10-31T19:34:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:34:22: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:34:22: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:34:22: PM2 log: App [haikal:0] online
2022-10-31T19:34:34: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:34:34: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:34:34: PM2 log: App [haikal:0] online
2022-10-31T19:34:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:34:48: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:34:48: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:34:48: PM2 log: App [haikal:0] online
2022-10-31T19:35:06: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:35:06: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:35:06: PM2 log: App [haikal:0] online
2022-10-31T19:35:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:35:21: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:35:21: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:35:21: PM2 log: App [haikal:0] online
2022-10-31T19:35:36: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:35:36: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:35:36: PM2 log: App [haikal:0] online
2022-10-31T19:35:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:35:50: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:35:50: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:35:50: PM2 log: App [haikal:0] online
2022-10-31T19:36:09: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:36:09: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:36:09: PM2 log: App [haikal:0] online
2022-10-31T19:36:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:36:26: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:36:26: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:36:26: PM2 log: App [haikal:0] online
2022-10-31T19:36:42: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:36:42: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:36:42: PM2 log: App [haikal:0] online
2022-10-31T19:36:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:36:59: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:36:59: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:36:59: PM2 log: App [haikal:0] online
2022-10-31T19:37:15: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:37:15: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:37:15: PM2 log: App [haikal:0] online
2022-10-31T19:37:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:37:27: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:37:27: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:37:27: PM2 log: App [haikal:0] online
2022-10-31T19:37:42: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:37:42: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:37:42: PM2 log: App [haikal:0] online
2022-10-31T19:37:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:37:55: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:37:55: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:37:55: PM2 log: App [haikal:0] online
2022-10-31T19:38:11: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:38:11: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:38:11: PM2 log: App [haikal:0] online
2022-10-31T19:38:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:38:37: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:38:37: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:38:37: PM2 log: App [haikal:0] online
2022-10-31T19:38:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:39:02: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:39:02: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:39:02: PM2 log: App [haikal:0] online
2022-10-31T19:39:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:39:27: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:39:27: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:39:27: PM2 log: App [haikal:0] online
2022-10-31T19:39:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:39:52: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:39:52: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:39:52: PM2 log: App [haikal:0] online
2022-10-31T19:40:13: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:40:13: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:40:13: PM2 log: App [haikal:0] online
2022-10-31T19:40:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:40:36: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:40:36: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:40:36: PM2 log: App [haikal:0] online
2022-10-31T19:40:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:40:56: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:40:56: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:40:56: PM2 log: App [haikal:0] online
2022-10-31T19:41:13: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:41:13: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:41:13: PM2 log: App [haikal:0] online
2022-10-31T19:41:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:41:31: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:41:31: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:41:31: PM2 log: App [haikal:0] online
2022-10-31T19:41:42: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:41:43: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:41:43: PM2 log: App [haikal:0] online
2022-10-31T19:41:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:41:55: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:41:55: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:41:55: PM2 log: App [haikal:0] online
2022-10-31T19:42:08: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:42:08: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:42:08: PM2 log: App [haikal:0] online
2022-10-31T19:42:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:42:26: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:42:26: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:42:26: PM2 log: App [haikal:0] online
2022-10-31T19:42:46: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:42:46: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:42:46: PM2 log: App [haikal:0] online
2022-10-31T19:42:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:43:05: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:43:05: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:43:05: PM2 log: App [haikal:0] online
2022-10-31T19:43:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:43:18: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:43:18: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:43:18: PM2 log: App [haikal:0] online
2022-10-31T19:43:30: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:43:30: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:43:30: PM2 log: App [haikal:0] online
2022-10-31T19:43:45: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:43:45: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:43:45: PM2 log: App [haikal:0] online
2022-10-31T19:43:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:43:56: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:43:56: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:43:56: PM2 log: App [haikal:0] online
2022-10-31T19:44:07: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:44:07: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:44:07: PM2 log: App [haikal:0] online
2022-10-31T19:44:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:44:30: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:44:30: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:44:30: PM2 log: App [haikal:0] online
2022-10-31T19:44:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:44:54: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:44:54: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:44:54: PM2 log: App [haikal:0] online
2022-10-31T19:45:15: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:45:15: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:45:15: PM2 log: App [haikal:0] online
2022-10-31T19:45:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:45:36: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:45:36: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:45:36: PM2 log: App [haikal:0] online
2022-10-31T19:45:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:45:49: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:45:49: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:45:49: PM2 log: App [haikal:0] online
2022-10-31T19:46:03: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:46:03: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:46:03: PM2 log: App [haikal:0] online
2022-10-31T19:46:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:46:17: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:46:17: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:46:17: PM2 log: App [haikal:0] online
2022-10-31T19:46:36: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:46:36: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:46:36: PM2 log: App [haikal:0] online
2022-10-31T19:46:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:46:49: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:46:49: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:46:49: PM2 log: App [haikal:0] online
2022-10-31T19:47:01: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:47:01: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:47:01: PM2 log: App [haikal:0] online
2022-10-31T19:47:14: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:47:14: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:47:14: PM2 log: App [haikal:0] online
2022-10-31T19:47:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:47:27: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:47:27: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:47:27: PM2 log: App [haikal:0] online
2022-10-31T19:47:42: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:47:42: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:47:42: PM2 log: App [haikal:0] online
2022-10-31T19:47:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:47:54: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:47:54: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:47:54: PM2 log: App [haikal:0] online
2022-10-31T19:48:09: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:48:09: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:48:09: PM2 log: App [haikal:0] online
2022-10-31T19:48:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:48:28: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:48:28: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:48:28: PM2 log: App [haikal:0] online
2022-10-31T19:48:42: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:48:42: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:48:42: PM2 log: App [haikal:0] online
2022-10-31T19:48:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:49:00: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:49:00: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:49:00: PM2 log: App [haikal:0] online
2022-10-31T19:49:12: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:49:12: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:49:12: PM2 log: App [haikal:0] online
2022-10-31T19:49:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:49:23: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:49:23: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:49:23: PM2 log: App [haikal:0] online
2022-10-31T19:49:35: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:49:35: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:49:35: PM2 log: App [haikal:0] online
2022-10-31T19:49:47: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:49:47: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:49:47: PM2 log: App [haikal:0] online
2022-10-31T19:49:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:49:59: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:49:59: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:49:59: PM2 log: App [haikal:0] online
2022-10-31T19:50:12: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:50:12: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:50:12: PM2 log: App [haikal:0] online
2022-10-31T19:50:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:50:23: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:50:23: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:50:23: PM2 log: App [haikal:0] online
2022-10-31T19:50:36: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:50:36: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:50:36: PM2 log: App [haikal:0] online
2022-10-31T19:50:47: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:50:47: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:50:47: PM2 log: App [haikal:0] online
2022-10-31T19:50:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:50:57: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:50:57: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:50:57: PM2 log: App [haikal:0] online
2022-10-31T19:51:08: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:51:08: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:51:08: PM2 log: App [haikal:0] online
2022-10-31T19:51:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:51:21: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:51:21: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:51:21: PM2 log: App [haikal:0] online
2022-10-31T19:51:36: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:51:36: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:51:36: PM2 log: App [haikal:0] online
2022-10-31T19:51:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:51:49: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:51:49: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:51:49: PM2 log: App [haikal:0] online
2022-10-31T19:52:00: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:52:00: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:52:00: PM2 log: App [haikal:0] online
2022-10-31T19:52:11: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:52:11: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:52:11: PM2 log: App [haikal:0] online
2022-10-31T19:52:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:52:22: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:52:22: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:52:22: PM2 log: App [haikal:0] online
2022-10-31T19:52:35: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:52:35: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:52:35: PM2 log: App [haikal:0] online
2022-10-31T19:52:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:52:48: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:52:48: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:52:48: PM2 log: App [haikal:0] online
2022-10-31T19:53:03: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:53:03: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:53:03: PM2 log: App [haikal:0] online
2022-10-31T19:53:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:53:18: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:53:18: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:53:18: PM2 log: App [haikal:0] online
2022-10-31T19:53:36: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:53:36: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:53:36: PM2 log: App [haikal:0] online
2022-10-31T19:53:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:53:51: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:53:51: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:53:51: PM2 log: App [haikal:0] online
2022-10-31T19:54:03: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:54:03: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:54:03: PM2 log: App [haikal:0] online
2022-10-31T19:54:15: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:54:15: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:54:15: PM2 log: App [haikal:0] online
2022-10-31T19:54:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:54:26: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:54:26: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:54:26: PM2 log: App [haikal:0] online
2022-10-31T19:54:39: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:54:39: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:54:39: PM2 log: App [haikal:0] online
2022-10-31T19:54:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:54:50: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:54:50: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:54:50: PM2 log: App [haikal:0] online
2022-10-31T19:55:01: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:55:01: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:55:01: PM2 log: App [haikal:0] online
2022-10-31T19:55:15: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:55:15: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:55:15: PM2 log: App [haikal:0] online
2022-10-31T19:55:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:55:26: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:55:26: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:55:26: PM2 log: App [haikal:0] online
2022-10-31T19:55:37: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:55:37: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:55:37: PM2 log: App [haikal:0] online
2022-10-31T19:55:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:55:50: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:55:50: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:55:50: PM2 log: App [haikal:0] online
2022-10-31T19:56:01: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:56:01: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:56:01: PM2 log: App [haikal:0] online
2022-10-31T19:56:12: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:56:12: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:56:12: PM2 log: App [haikal:0] online
2022-10-31T19:56:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:56:24: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:56:24: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:56:24: PM2 log: App [haikal:0] online
2022-10-31T19:56:37: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:56:37: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:56:37: PM2 log: App [haikal:0] online
2022-10-31T19:56:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:56:50: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:56:50: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:56:50: PM2 log: App [haikal:0] online
2022-10-31T19:57:03: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:57:03: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:57:03: PM2 log: App [haikal:0] online
2022-10-31T19:57:16: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:57:16: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:57:16: PM2 log: App [haikal:0] online
2022-10-31T19:57:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:57:28: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:57:28: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:57:28: PM2 log: App [haikal:0] online
2022-10-31T19:57:41: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:57:41: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:57:41: PM2 log: App [haikal:0] online
2022-10-31T19:57:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:57:53: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:57:53: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:57:53: PM2 log: App [haikal:0] online
2022-10-31T19:58:06: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:58:06: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:58:06: PM2 log: App [haikal:0] online
2022-10-31T19:58:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:58:18: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:58:18: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:58:18: PM2 log: App [haikal:0] online
2022-10-31T19:58:34: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:58:34: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:58:34: PM2 log: App [haikal:0] online
2022-10-31T19:58:47: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:58:47: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:58:47: PM2 log: App [haikal:0] online
2022-10-31T19:58:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:59:01: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:59:01: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:59:01: PM2 log: App [haikal:0] online
2022-10-31T19:59:15: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:59:15: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:59:15: PM2 log: App [haikal:0] online
2022-10-31T19:59:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:59:34: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:59:34: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:59:34: PM2 log: App [haikal:0] online
2022-10-31T19:59:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T19:59:49: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T19:59:49: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T19:59:49: PM2 log: App [haikal:0] online
2022-10-31T20:00:02: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:00:02: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:00:03: PM2 log: App [haikal:0] online
2022-10-31T20:00:15: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:00:15: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:00:15: PM2 log: App [haikal:0] online
2022-10-31T20:00:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:00:28: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:00:28: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:00:28: PM2 log: App [haikal:0] online
2022-10-31T20:00:40: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:00:40: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:00:40: PM2 log: App [haikal:0] online
2022-10-31T20:00:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:00:54: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:00:54: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:00:54: PM2 log: App [haikal:0] online
2022-10-31T20:01:08: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:01:08: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:01:08: PM2 log: App [haikal:0] online
2022-10-31T20:01:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:01:21: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:01:21: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:01:21: PM2 log: App [haikal:0] online
2022-10-31T20:01:34: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:01:34: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:01:34: PM2 log: App [haikal:0] online
2022-10-31T20:01:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:01:49: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:01:49: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:01:49: PM2 log: App [haikal:0] online
2022-10-31T20:02:05: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:02:05: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:02:05: PM2 log: App [haikal:0] online
2022-10-31T20:02:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:02:18: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:02:18: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:02:18: PM2 log: App [haikal:0] online
2022-10-31T20:02:31: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:02:31: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:02:31: PM2 log: App [haikal:0] online
2022-10-31T20:02:43: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:02:43: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:02:43: PM2 log: App [haikal:0] online
2022-10-31T20:02:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:02:57: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:02:57: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:02:57: PM2 log: App [haikal:0] online
2022-10-31T20:03:12: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:03:12: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:03:12: PM2 log: App [haikal:0] online
2022-10-31T20:03:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:03:25: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:03:25: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:03:26: PM2 log: App [haikal:0] online
2022-10-31T20:03:37: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:03:37: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:03:37: PM2 log: App [haikal:0] online
2022-10-31T20:03:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:03:50: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:03:50: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:03:50: PM2 log: App [haikal:0] online
2022-10-31T20:04:04: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:04:04: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:04:04: PM2 log: App [haikal:0] online
2022-10-31T20:04:17: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:04:17: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:04:17: PM2 log: App [haikal:0] online
2022-10-31T20:04:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:04:33: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:04:33: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:04:33: PM2 log: App [haikal:0] online
2022-10-31T20:04:46: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:04:46: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:04:46: PM2 log: App [haikal:0] online
2022-10-31T20:04:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:04:59: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:04:59: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:04:59: PM2 log: App [haikal:0] online
2022-10-31T20:05:13: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:05:13: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:05:13: PM2 log: App [haikal:0] online
2022-10-31T20:05:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:05:26: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:05:26: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:05:26: PM2 log: App [haikal:0] online
2022-10-31T20:05:39: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:05:39: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:05:39: PM2 log: App [haikal:0] online
2022-10-31T20:05:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:05:52: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:05:52: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:05:52: PM2 log: App [haikal:0] online
2022-10-31T20:06:09: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:06:09: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:06:09: PM2 log: App [haikal:0] online
2022-10-31T20:06:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:06:28: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:06:28: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:06:28: PM2 log: App [haikal:0] online
2022-10-31T20:06:43: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:06:43: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:06:43: PM2 log: App [haikal:0] online
2022-10-31T20:06:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:06:57: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:06:57: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:06:57: PM2 log: App [haikal:0] online
2022-10-31T20:07:10: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:07:10: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:07:10: PM2 log: App [haikal:0] online
2022-10-31T20:07:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:07:30: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:07:30: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:07:30: PM2 log: App [haikal:0] online
2022-10-31T20:07:45: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:07:45: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:07:45: PM2 log: App [haikal:0] online
2022-10-31T20:07:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:08:05: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:08:05: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:08:05: PM2 log: App [haikal:0] online
2022-10-31T20:08:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:08:25: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:08:25: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:08:25: PM2 log: App [haikal:0] online
2022-10-31T20:08:45: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:08:45: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:08:45: PM2 log: App [haikal:0] online
2022-10-31T20:08:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:08:59: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:08:59: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:08:59: PM2 log: App [haikal:0] online
2022-10-31T20:09:15: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:09:15: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:09:15: PM2 log: App [haikal:0] online
2022-10-31T20:09:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:09:28: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:09:28: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:09:28: PM2 log: App [haikal:0] online
2022-10-31T20:09:42: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:09:42: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:09:42: PM2 log: App [haikal:0] online
2022-10-31T20:09:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:10:00: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:10:00: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:10:00: PM2 log: App [haikal:0] online
2022-10-31T20:10:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:10:20: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:10:20: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:10:20: PM2 log: App [haikal:0] online
2022-10-31T20:10:40: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:10:40: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:10:40: PM2 log: App [haikal:0] online
2022-10-31T20:10:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:10:55: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:10:55: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:10:55: PM2 log: App [haikal:0] online
2022-10-31T20:11:09: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:11:09: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:11:09: PM2 log: App [haikal:0] online
2022-10-31T20:11:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:11:24: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:11:24: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:11:24: PM2 log: App [haikal:0] online
2022-10-31T20:11:41: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:11:41: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:11:41: PM2 log: App [haikal:0] online
2022-10-31T20:11:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:11:55: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:11:55: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:11:55: PM2 log: App [haikal:0] online
2022-10-31T20:12:11: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:12:11: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:12:12: PM2 log: App [haikal:0] online
2022-10-31T20:12:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:12:25: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:12:25: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:12:25: PM2 log: App [haikal:0] online
2022-10-31T20:12:39: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:12:39: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:12:39: PM2 log: App [haikal:0] online
2022-10-31T20:12:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:12:52: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:12:52: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:12:52: PM2 log: App [haikal:0] online
2022-10-31T20:13:07: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:13:07: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:13:07: PM2 log: App [haikal:0] online
2022-10-31T20:13:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:13:22: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:13:22: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:13:22: PM2 log: App [haikal:0] online
2022-10-31T20:13:37: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:13:37: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:13:37: PM2 log: App [haikal:0] online
2022-10-31T20:13:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:13:54: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:13:54: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:13:54: PM2 log: App [haikal:0] online
2022-10-31T20:14:07: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:14:07: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:14:07: PM2 log: App [haikal:0] online
2022-10-31T20:14:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:14:22: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:14:22: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:14:22: PM2 log: App [haikal:0] online
2022-10-31T20:14:36: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:14:36: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:14:36: PM2 log: App [haikal:0] online
2022-10-31T20:14:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:14:48: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:14:48: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:14:48: PM2 log: App [haikal:0] online
2022-10-31T20:15:03: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:15:03: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:15:03: PM2 log: App [haikal:0] online
2022-10-31T20:15:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:15:17: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:15:17: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:15:17: PM2 log: App [haikal:0] online
2022-10-31T20:15:34: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:15:34: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:15:34: PM2 log: App [haikal:0] online
2022-10-31T20:15:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:15:48: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:15:48: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:15:48: PM2 log: App [haikal:0] online
2022-10-31T20:16:05: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:16:05: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:16:05: PM2 log: App [haikal:0] online
2022-10-31T20:16:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:16:19: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:16:19: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:16:20: PM2 log: App [haikal:0] online
2022-10-31T20:16:36: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:16:36: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:16:36: PM2 log: App [haikal:0] online
2022-10-31T20:16:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:16:50: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:16:50: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:16:50: PM2 log: App [haikal:0] online
2022-10-31T20:17:08: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:17:08: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:17:08: PM2 log: App [haikal:0] online
2022-10-31T20:17:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:17:21: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:17:21: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:17:21: PM2 log: App [haikal:0] online
2022-10-31T20:17:35: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:17:35: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:17:35: PM2 log: App [haikal:0] online
2022-10-31T20:17:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:17:48: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:17:48: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:17:48: PM2 log: App [haikal:0] online
2022-10-31T20:18:01: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:18:01: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:18:01: PM2 log: App [haikal:0] online
2022-10-31T20:18:16: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:18:16: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:18:16: PM2 log: App [haikal:0] online
2022-10-31T20:18:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:18:33: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:18:33: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:18:33: PM2 log: App [haikal:0] online
2022-10-31T20:18:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:18:53: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:18:53: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:18:53: PM2 log: App [haikal:0] online
2022-10-31T20:19:16: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:19:16: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:19:16: PM2 log: App [haikal:0] online
2022-10-31T20:19:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:19:34: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:19:34: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:19:34: PM2 log: App [haikal:0] online
2022-10-31T20:19:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:19:51: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:19:51: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:19:51: PM2 log: App [haikal:0] online
2022-10-31T20:20:06: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:20:06: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:20:06: PM2 log: App [haikal:0] online
2022-10-31T20:20:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:20:22: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:20:22: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:20:22: PM2 log: App [haikal:0] online
2022-10-31T20:20:37: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:20:37: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:20:37: PM2 log: App [haikal:0] online
2022-10-31T20:20:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:20:53: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:20:53: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:20:53: PM2 log: App [haikal:0] online
2022-10-31T20:21:13: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:21:13: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:21:13: PM2 log: App [haikal:0] online
2022-10-31T20:21:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:21:33: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:21:33: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:21:33: PM2 log: App [haikal:0] online
2022-10-31T20:21:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:21:51: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:21:51: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:21:51: PM2 log: App [haikal:0] online
2022-10-31T20:22:09: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:22:09: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:22:09: PM2 log: App [haikal:0] online
2022-10-31T20:22:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:22:27: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:22:27: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:22:27: PM2 log: App [haikal:0] online
2022-10-31T20:22:46: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:22:46: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:22:46: PM2 log: App [haikal:0] online
2022-10-31T20:22:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:23:03: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:23:03: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:23:03: PM2 log: App [haikal:0] online
2022-10-31T20:23:17: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:23:17: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:23:17: PM2 log: App [haikal:0] online
2022-10-31T20:23:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:23:31: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:23:31: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:23:31: PM2 log: App [haikal:0] online
2022-10-31T20:23:43: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:23:43: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:23:43: PM2 log: App [haikal:0] online
2022-10-31T20:23:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:23:59: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:23:59: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:23:59: PM2 log: App [haikal:0] online
2022-10-31T20:24:13: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:24:13: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:24:13: PM2 log: App [haikal:0] online
2022-10-31T20:24:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:24:26: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:24:26: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:24:26: PM2 log: App [haikal:0] online
2022-10-31T20:24:43: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:24:43: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:24:43: PM2 log: App [haikal:0] online
2022-10-31T20:24:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:25:00: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:25:00: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:25:00: PM2 log: App [haikal:0] online
2022-10-31T20:25:14: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:25:14: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:25:14: PM2 log: App [haikal:0] online
2022-10-31T20:25:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:25:29: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:25:29: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:25:29: PM2 log: App [haikal:0] online
2022-10-31T20:25:44: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:25:44: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:25:44: PM2 log: App [haikal:0] online
2022-10-31T20:25:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:25:55: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:25:55: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:25:55: PM2 log: App [haikal:0] online
2022-10-31T20:26:07: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:26:07: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:26:07: PM2 log: App [haikal:0] online
2022-10-31T20:26:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:26:18: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:26:18: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:26:18: PM2 log: App [haikal:0] online
2022-10-31T20:26:33: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:26:33: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:26:33: PM2 log: App [haikal:0] online
2022-10-31T20:26:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:26:49: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:26:49: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:26:49: PM2 log: App [haikal:0] online
2022-10-31T20:27:02: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:27:02: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:27:02: PM2 log: App [haikal:0] online
2022-10-31T20:27:17: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:27:17: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:27:17: PM2 log: App [haikal:0] online
2022-10-31T20:27:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:27:32: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:27:32: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:27:32: PM2 log: App [haikal:0] online
2022-10-31T20:27:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:27:48: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:27:48: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:27:48: PM2 log: App [haikal:0] online
2022-10-31T20:28:00: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:28:00: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:28:00: PM2 log: App [haikal:0] online
2022-10-31T20:28:11: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:28:11: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:28:11: PM2 log: App [haikal:0] online
2022-10-31T20:28:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:28:22: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:28:22: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:28:22: PM2 log: App [haikal:0] online
2022-10-31T20:28:33: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:28:33: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:28:33: PM2 log: App [haikal:0] online
2022-10-31T20:28:45: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:28:45: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:28:45: PM2 log: App [haikal:0] online
2022-10-31T20:28:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:28:55: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:28:55: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:28:55: PM2 log: App [haikal:0] online
2022-10-31T20:29:06: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:29:06: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:29:06: PM2 log: App [haikal:0] online
2022-10-31T20:29:17: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:29:17: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:29:17: PM2 log: App [haikal:0] online
2022-10-31T20:29:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2022-10-31T20:29:27: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:29:27: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:29:27: PM2 log: App [haikal:0] online
2022-10-31T20:29:39: PM2 log: App [haikal:0] exited with code [1] via signal [SIGINT]
2022-10-31T20:29:39: PM2 log: App [haikal:0] starting in -fork mode-
2022-10-31T20:29:39: PM2 log: App [haikal:0] online
